server:
  port: 8081
spring:
  application:
    name: configuration-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/lenyn15/SystemSales-SIDECOM.git
          search-paths: configuration
        default-label: master
  security:
    user:
      name: root
      password: v4L1d0